name: Validate Localizations

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run validate.sh
        run: ./validate.sh
